modLoader="javafml"
loaderVersion="[40,)"
license="Attribution-ShareAlike 4.0 International"
logoBlur=false
logoFile="jeweler_logo.png"
[[mods]]
modId="jeweler"
version="1.19.4-1.0.0a"
displayName="Jeweler"
displayURL="https://www.curseforge.com/minecraft/mc-mods/jeweler"
authors="Walker Case"
description='''
Adds various types of jewelry and gems for your enjoyment!
'''
[[dependencies.jeweler]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.jeweler]]
    modId="curios"
    mandatory=true
    versionRange="[1.18,)"
    ordering="NONE"
    side="BOTH"
[modproperties.jeweler]
    catalogueImageIcon="jeweler_logo.png"