modLoader="javafml"
loaderVersion="[45,)"
license="Attribution-ShareAlike 4.0 International"
logoFile="jeweler_logo.png"
logoBlur=false
[[mods]]
modId="jeweler"
version="${file.jarVersion}"
displayName="Jeweler"
displayURL="https://www.curseforge.com/minecraft/mc-mods/jeweler"
authors="Walker Case"
description='''
Adds various types of jewelry and gems for your enjoyment!
'''
[[dependencies.jeweler]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.jeweler]]
    modId="curios"
    mandatory=true
    versionRange="[1.19,)"
    ordering="NONE"
    side="BOTH"
[modproperties.jeweler]
    catalogueImageIcon="jeweler_logo.png"